Registry.require(["helper","convert"],function(){var p=Registry.get("helper"),r=Registry.get("convert"),u,w,A=function(a){return a&&"http"==a.substr(0,4)},B={internal:!0,cookie:!0,"user-agent":!0,referer:!0,origin:!0,host:!0,"proxy-connection":!0,"accept-encoding":!0,"accept-charset":!0},E={"cache-control":"no-cache",pragma:"no-cache"},F={"cache-control":"max-age=0, must-revalidate"},v=function(a){return{responseXML:"",responseText:"",response:null,readyState:4,responseHeaders:"",status:0,statusText:"",
error:a||"Forbidden"}},x=function(a){if("Blob"===a.type)return new Blob([r.str2arrbuf(a.value)]);if("File"===a.type)return new File([r.str2arrbuf(a.value)],a.name,{type:a.meta,lastModified:a.lastModified||Date.now()});if("FormData"==a.type){var d=new FormData;Object.keys(a.value).forEach(function(b){var c="Array"===a.value[b].type,e=x(a.value[b]),l=c?e:[e];l.forEach(function(a,c){d.append(b,l[c])})});return d}if("Array"===a.type||"Object"===a.type){var h,c,e;"Object"===a?(e=Object.keys(a.value),c=
function(a){return a<e.length?e[a]:null},h={}):(c=function(b){return b<a.value.length?b:null},h=[]);for(var k,n=0;null!==(k=c(n));n++)h[k]=x(a.value[k]);return h}return a.value},G=function(a,d,h){void 0===h&&(h={});var c=p.assign({},d||{}),e=function(a,b){if(c[a])c[a]("function"==typeof b?b():b)};d=function(a,b){c[a]&&(e(a,b),c[a]=null)};if(h.internal||A(a.url)){var k=window.fetch&&a.url&&"http"==a.url.substr(0,4),n=!w&&a.anonymous,b=a.fetch;return k&&(n||b)?C(a,c,h,d,e):y(a,c,h,d,e)}console.warn("xhr: invalid scheme of url:",
a.url);a=v("Invalid scheme");d("onerror",a);d("ondone",a)},z="tm-finalurl"+rea.runtime.short_id.toLowerCase(),D="tm-setcookie"+rea.runtime.short_id.toLowerCase(),C=function(a,d,h,c,e){var k=function(a){var b=[],c,m;a.headers&&(c=a.headers.get(z)||a.url,a.headers.forEach(function(a,m){var c=m.toLowerCase();-1==[z,D].indexOf(c)&&b.push(c+":"+a)}),(m=a.headers.get(D))&&b.push("set-cookie:"+m));return{readyState:4,responseHeaders:b.join("\n"),finalUrl:c,status:a.status,statusText:a.statusText}},n=function(b){(function(a,
b){for(var m=[],f=0,c=a.length;f<c;f+=b)m.push(a.slice(f,b+f));return m})(b,parseInt(a.partialSize)).forEach(function(a){e("onpartial",{partial:a})})};try{var b={};b.method=a.method||"GET";b.redirect="follow";if(a.nocache||a.revalidate)b.cache="no-store";b.credentials=a.anonymous?"omit":"include";if(a.headers){var q={};Object.keys(a.headers).forEach(function(b){var c=b,d=a.headers[b];if(u)B[b.toLowerCase()]&&(c=u+b,d=null===d?"":r.encodeS(d));else if(null===d)return;q[c]=d});b.headers=new window.Headers(q)}void 0!==
a.data&&(b.body="typified"===a.data_type?x(a.data):"string"===typeof a.data?a.data:JSON.stringify(a.data));void 0!==a.timeout&&(b.timeout=a.timeout);var p=window.fetch(a.url,b).then(function(b){var g=k(b);(0!==g.status||200>g.status||300<=g.status)&&0<a.retries?(a.retries--,C(a,d,h,c,e)):function(){var c;if(b.ok)void 0!==a.responseType?function(){if(!a.convertBinary||"arraybuffer"!=a.responseType&&"blob"!=a.responseType){if("arraybuffer"==a.responseType)return b.arrayBuffer();if("blob"==a.responseType)return b.blob();
console.warn("xhr: responseType",a.responseType," is not implemented!");return b.text()}return b.arrayBuffer().then(function(a){return r.arrbuf2str(a)})}().then(function(a){g.response=a;c()}):b.text().then(function(a){g.responseText=a;c()});else return g.responseXML=null,g.responseText="",g.response=null,{done:function(a){a()}};return{done:function(a){c=a}}}().done(function(){if(a.partialSize&&d.onpartial){var b=a.convertBinary&&g.response?g.response:g.responseText;["response","responseText","responseXML"].forEach(function(a){delete g[a]});
b&&(b.length>a.partialSize?n(b):g.response_data=b)}c("onload",g);c("ondone",g)})}).catch(function(a){a=k({status:408,statusText:a.message||"Request Timeout"});c("onerror",a);c("ondone",a)})}catch(l){console.error(l.stack),b=v(l.message),c("onerror",b),c("ondone",b)}return{abort:function(){try{p.abort&&p.abort()}catch(a){}}}},y=function(a,d,h,c,e){var k,n,b=new XMLHttpRequest(a.anonymous?{mozAnon:!0}:{}),q=function(m){var f="",c=a.url;if(2<=b.readyState&&(f=b.getAllResponseHeaders(),4==b.readyState)){f&&
(f=f.replace(/tm-finalurl[0-9a-zA-Z]*\: .*[\r\n]{1,2}/i,""),f=f.replace(/tm-setcookie[0-9a-zA-Z]*\:/i,"set-cookie:"));var d;if(d=b.getResponseHeader(z))c=d}f={readyState:b.readyState,responseHeaders:f,finalUrl:c,status:4==b.readyState?b.status:0,statusText:4==b.readyState?b.statusText:""};m&&4==b.readyState?(b.responseType?(f.responseXML=null,f.responseText=null,f.responseType=b.responseType):(f.responseXML=b.responseXML,f.responseText=b.responseText),f.response=b.response):(f.responseXML=null,f.responseText=
"",f.response=null);return f},w=function(b){(function(a,b){for(var m=[],c=0,d=a.length;c<d;c+=b)m.push(a.slice(c,b+c));return m})(b,parseInt(a.partialSize)).forEach(function(a){e("onpartial",{partial:a})})},l={onload:function(){var b=q(!0);(0!==b.status||200>b.status||300<=b.status)&&0<a.retries?(a.retries--,y(a,d,h,c,e)):function(){if(a.convertBinary&&b.response){var c=b.responseType?b.responseType.toLowerCase():"";k&&c!==k&&console.warn("xhr: requested responseType "+k+" differs from received "+
c);if("document"==c||"document"==k)if("string"==typeof b.response)c=p.getStringBetweenTags(b.responseHeaders.toLowerCase(),"content-type:","\n").trim()||"text/html",b.response={data:b.response,contentType:c};else{var c=b.response,d=c.contentType||"text/html";try{b.response={data:(new XMLSerializer).serializeToString(c.documentElement),contentType:d}}catch(g){var e="unable to serialize content type "+d;console.warn("xhr: ",e,c);b.response={error:e,contentType:d}}}else if("json"==c)b.response=JSON.stringify(b.response);
else{if("blob"==c){var h,l=new FileReader;l.onload=function(){b.response=r.arrbuf2str(l.result);h()};l.readAsArrayBuffer(b.response);return{done:function(a){h=a}}}"arraybuffer"==c&&(b.response=r.arrbuf2str(b.response))}}return{done:function(a){a()}}}().done(function(){if(a.partialSize&&d.onpartial){var f=a.convertBinary&&b.response?b.response:b.responseText;["response","responseText","responseXML"].forEach(function(a){delete b[a]});f&&(f.length>a.partialSize?w(f):b.response_data=f)}c("onload",b);
4==b.readyState&&c("ondone",b)})},onerror:function(){var b=q();4==b.readyState&&200!=b.status&&0!=b.status&&0<a.retries?(a.retries--,y(a,d,h,c,e)):(c("onerror",b),c("ondone",b))},onloadstart:function(){e("onloadstart",function(){return q()})},onreadystatechange:function(){e("onreadystatechange",function(){return q()})},onprogress:function(a){e("onprogress",function(){var c=q(),d=c;void 0===d&&(d={});try{var e=null,g=null;if(a.lengthComputable||0<a.total)e=a.loaded,g=a.total;else{var h=b.responseType&&
-1==["","text"].indexOf(b.responseType)?null:b.responseText,k=Number(p.getStringBetweenTags(c.responseHeaders.toLowerCase(),"content-length:","\n").trim()),l=2<c.readyState&&h?h.length:0;0==k&&(k=-1);e=a.loaded||l;g=a.total||k}d.lengthComputable=a.lengthComputable;d.loaded=e;d.done=e;d.position=e;d.total=g;d.totalSize=g}catch(n){}return d})},ontimeout:function(){var a=q();c("ontimeout");c("ondone",a)},onabort:function(){var a=v("aborted");c("ondone",a)}},g=0==Object.keys(l).concat(["ondone"]).filter(function(a){return!!d[a]}).length;
if(g)throw Error("Synchronous XHR is not supported anymore");Object.keys(l).forEach(function(a){if(d[a]||-1!=["ontimeout","onload","onerror","onabort"].indexOf(a))b[a]=l[a]});try{if(!h.internal&&!A(a.url))throw Error("Invalid scheme of url: "+a.url);b.open(a.method,a.url,!g,a.user,a.password);if(a.headers||a.nocache||a.revalidate){var t={};a.headers&&p.assign(t,a.headers);a.nocache?p.assign(t,E):a.revalidate&&p.assign(t,F);Object.keys(t).forEach(function(a){var c=a,d=t[a];if(u)B[a.toLowerCase()]&&
(c=u+a,d=null===d?"":r.encodeS(d));else if(null===d)return;try{b.setRequestHeader(c,d)}catch(e){console.warn("xhr: rejected header",c,t[a])}})}void 0!==a.overrideMimeType&&b.overrideMimeType(a.overrideMimeType);void 0!==a.responseType&&(k=a.responseType.toLowerCase(),-1==["document","json"].indexOf(k)&&(b.responseType=k));void 0!==a.timeout&&(b.timeout=a.timeout);void 0!==a.data?("typified"===a.data_type?b.send(x(a.data)):"string"===typeof a.data?b.send(a.data):b.send(JSON.stringify(a.data)),d.onprogress&&
b.upload&&(b.upload.onprogress=l.onprogress)):b.send()}catch(m){console.error(m.stack),g=v(m.message),c("onerror",g),c("ondone",g)}n=n||{};return p.copy({abort:function(){b.abort()}},n)};Registry.register("xmlhttprequest","5873",function(a,d){w=d;u=a;return{run:G,makeErrorResponse:v}})});
